# 1.Numpy的属性介绍

## 1.1创建ndarray对象

In [ ]:
# numpy -->和数学操作相关的库，numpy的数组是多维的，并且是固定类型，numpy的数组是ndarray，主要用于：矩阵运算
# 1.导包
import numpy as np
#2.创建numpy的ndarray对象。
arr1 = np.arange(15).reshape(3,5)
print(arr1)

## 1.2 演示numpy的常用属性

In [ ]:
print(f"numpy的轴：{arr1.ndim}") #2
print(f"numpy的维度：{arr1.shape}") #（3,5）
print(f"numpy的元素类型{arr1.dtype}") #int64   64位 = 8字节
print(f"numpy的元素个数{arr1.size}") #15
print(f"numpy的元素占用字节数:{arr1.itemsize}") #8
print(f"numpy的元素类型：{type(arr1)}") #<class 'numpy.ndarray'>

# 2.创建Numpy的ndarrary对象

## 2.1 array()函数，把Python列表  -->ndarray对对象

In [ ]:
# 创建Python列表对象
my_list = [1,2,3,4,5]
print(type(my_list))  # <class 'list'>
arr2 = np.array(my_list)
print(type(arr2))# <class 'numpy.ndarray'>
print(arr2)

## 2.2 arange()函数,创建ndarray对象

In [ ]:
# arange(起始,结束,步长,dtype=类型)，类似于Python中的range
#1.创建ndarrary对象
arr3 = np.arange(0,10,2,dtype=np.int32)
print(arr3)
print(type(arr3))
print(f"元素类型：{arr3.dtype}")

## 2.3 随机数生成 ndarrary对象

In [ ]:
# 1. random.rand() 生成0.0 ~ 1.0之间的，包左不包右的，随机小数矩阵
arr4 = np.random.rand(3,5) # 3行5列
print(arr4)

In [ ]:
# 2. random.randint(起始值，结束值，size=(行,列)) 生成指定范围，包左不包右的，随机小数矩阵
arr5 = np.random.randint(0,10,size=(2,6)) # 0~10之间，2行6列
print(arr5)
print(type(arr5))

In [24]:
#3.random.uniform(起始值，结束值，size=(行,列)) 创建指定范围的随机矩阵,包左不包右
arr6 = np.random.uniform(3,9,size=(2,6))
print(arr6)
print(type(arr6))

[[4.18737312 7.39433543 5.43675137 8.61817157 6.64487112 4.48334695]
 [5.84002057 7.45573222 3.798124   3.9166223  3.40942794 8.46261792]]
<class 'numpy.ndarray'>


## 2.4 numpy的类型转换 astype()

In [26]:
# 1.创还能ndarray对象
arr7 = np.arange(1,10,dtype=np.float64)
print(arr7)
print(f"元素类型：{arr7.dtype}")


[1. 2. 3. 4. 5. 6. 7. 8. 9.]
元素类型：float64


In [27]:
# 2.类型转换
arr8 = arr7.astype(np.int32)
print(arr8)
print(f"元素类型：{arr8.dtype}")

[1 2 3 4 5 6 7 8 9]
元素类型：int32


## 2.5创建等比数列

In [32]:
#1.创建等比数列，参1：起始值(充当10的指数)，参2：结束值（充当10的指数)，参3：元素个数
arr9 = np.logspace(0,3,4)
# 2.打印ndarrary对象
print(arr9)
print(f"元素类型：{arr9.dtype}")

[   1.   10.  100. 1000.]
元素类型：float64


In [36]:
#3.创建等比数列，参1：起始值充当2的指数)，参2：结束值充当2的指数)，参3：元素个数
arr9 = np.logspace(0, 3, 4,base=2,dtype=np.int32)
# 4.打印ndarrary对象
print(arr9)
print(f"元素类型：{arr9.dtype}")

[1 2 4 8]
元素类型：int32


## 2.6 创建等差数列

In [ ]:
 # 1. 创建等差数列